### ISSUE TITLE
TypeError: bad argument type for built-in operation?

### ISSUE THREAD

**Issue by adriel** [FabioStrappazzonFHNW/ProjectionTransformer#1]
Hey, just trying to run the code today with ptyhon3 and getting this error, any ideas?
(I'm not experienced in python at all, so somewhat hard to debug for me)

Line 30 is `    transformedImage = geometric_transform(sourceImage, equirectangularToOrthographic)`

```python
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    transformedImage = geometric_transform(sourceImage, equirectangularToOrthographic)
  File "/home/mini/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 262, in geometric_transform
    extra_keywords)
TypeError: bad argument type for built-in operation
```

**Comment by FabioStrappazzonFHNW** [comment]
This error occurs when using the script with anything other than grayscale images.
Glymur treats images as 2D arrays if each pixel can be represented with a single value, as is the case with grayscale images. Other images are treated as 3D arrays. So the function passed to `geometric_transform()` needs to return a tuple of lenght 2 for grayscale images and a tuple of lenght 3 for any other image.

You can modify the script to make it work with other colorspaces:
Line 21: `return (resultY, resultX, output_coords[2]);`
Line 31: `savedJP2 = glymur.Jp2k(outdir + file, data=transformedImage)`

**Comment by adriel** [comment]
Thanks! That did the trick. (and adjusting the radius and imageWidth to my image dimensions.)
